apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/januschung/argocd
    targetRevision: main
    path: lab/aal/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: aal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
