replicaCount: 1
image:
  repository: ghcr.io/januschung/observation-bay
  tag: 6a5da00
imagePullSecrets:
  - name: ghcr-token
resources:
  requests:
    memory: '64Mi'
    cpu: '25m'
  limits:
    memory: '128Mi'
    cpu: '100m'
revisionHistoryLimit: 5
service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
ingress:
  enabled: true
  ingressClassName: traefik
  hostname: janusc.duckdns.org
  path: /
  pathType: Prefix
  servicePort: 80
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
