---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-token
  namespace: aal
spec:
  encryptedData:
    .dockerconfigjson: AgAA5TvwLhJ7aq9hk37An654INEdDs6FNlDzR6Ce0qtyphWEztwTYkK49A8ThjLPLsMapPKUxK0mLJ1Gj2Gy75n+mswC68wv7kIIzaELtS0CkHnNP8ZdJHdD19q3C7GKmJeJ1jK8pS7XfgVH12/suWKy3ZVK3ZoHm2ibmIrUmlMwxjkDmhF3i2oTmiZkT427IvxFuMdTbQtiz2FI060QHmS6WF51XuC5BvYdj5roVnJNDHMIf5AOZi6rQcFZ8uFJg8mkQoG9AaoK/qYm7UZp0E+za1d3fW+Zc+850lsTZN/8p557lYfy3t7NoWlsTMB8ZWfM+95qCMaBaccLGoz9tUYF6VV6jH0MGp3filQfY3dFc4v3wfGbKJEdMO1YQN9z2v3xCuTWCjoYCtiNiiDUVYCcizoHhoZJqoQM723GP7gJd1jeQLst4dMys9IynotPQDOCqDeDh3XKF5ToxVQ8RzN6mFxUdESMKf8XGJn8lv6urgZZCIUquHSyCkVpIPhCNVbQm0U7Nc75oZcZzK20HR6Qxx1pKskA5zYJ1XTcFE+1xT6oz5ko63Mu6fDRrBfroGsoaNUX+51iWuwQCmcA7MfAoMzHlXdl9nWhLMVsvP1uOOhmBP6DijbzOyaYU+an3ZbDTxcpDrICqE4T2OUcaa+g6iLcvDge2Xp/b9sSHHpB18/h4gBe/pMJW8MxsM4do2JuE7Izoq/kUrYg1eqF7VSr536wy8mak0gnjbpWne2UzplLCO4jSgXRPfbakQB4IFLpTJsJzbOS4Qc7jq+4ABDu/IBun/nxNYtuwY6IlwwyB3uLCEcIg0KXuHyx8Nw1H89G9KpNEsmrqac7VLUuQAT97xJcFqTtJso5hMOVez682QU8JHlCvGA4x4OyEUs5ldj5SfesUNkOm3krcfb/+VtZikW/UdDEK5zh+HwQSCFNaxDkGBA/ouNNecvJ8XBsvEA+7ke0KKYmsZivLdsUspnebGo0k2R2iKmPRN3e8/nAMbo03eV/Nrqbuf1I1+38OsgY
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-token
      namespace: aal
    type: kubernetes.io/dockerconfigjson
