name: 'Update Tag'
on:
  repository_dispatch:
    types: [update-tag]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-tag:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ github.event.client_payload.app_name }}
      TAG: ${{ github.event.client_payload.tag }}
      DEPLOYMENT_TYPE: ${{ github.event.client_payload.deployment_type }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v5

      - name: Install yq
        run: |
          sudo curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Update tag
        run: |
          cd lab/${APP_NAME}/chart
          if [[ "${DEPLOYMENT_TYPE}" ]]; then
            yq -i "${DEPLOYMENT_TYPE}.image.tag = \"${TAG}\"" values.yaml
          else
            yq -i ".image.tag = \"${TAG}\"" values.yaml
          fi

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "Automated update ${{ env.APP_NAME }} ${{ env.DEPLOYMENT_TYPE }} image tag to ${{ env.TAG }}"
          committer: "Janux Bot <no-reply@github.io>"
          author: "Janux Bot <no-reply@github.io>"
          branch: auto/update-branch-${{ env.APP_NAME }}
          title: "Automated PR to update ${{ env.APP_NAME }} ${{ env.DEPLOYMENT_TYPE }} image tag to ${{ env.TAG }}"
          body: "Automated PR from dispatch"
          base: main
          signoff: true
          delete-branch: true

      - name: Enable auto-merge
        run: |
          for i in {1..5}; do
            echo "Attempt $i: Trying to enable auto-merge..."
            gh pr merge --merge --auto "auto/update-branch-${{ env.APP_NAME }}" && break
            echo "Auto-merge failed. Retrying in 10 seconds..."
            sleep 10
          done
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
